### ISSUE TITLE
Update the samples

### ISSUE THREAD

**Issue by mwz** [mwz/sonar-scala#41]
It would be good to have examples for:
  - [x] sbt (single and multi-module) - #66, @mwz
  - [x] maven (single and multi-module) - #66, @mwz
  - [ ] maven mixed Scala/Java - #67, @mwz
  - [x] gradle (single and multi-module) - #62, @mwz

**Comment by BalmungSan** [comment]
I'm wondering if we could create test suites that could mock those environments. Especially for the Scoverage Plugin.

**Comment by BalmungSan** [comment]
Absolutely, that would be great, and also that would force us to maintain the samples updated.

Just one question, If we, in a _(distant?)_ future, add support for Windows, there could be a way to test it in Circle too?

**Comment by mwz** [comment]
No, CircleCI doesn't support Windows - we would probably need to use something like https://www.appveyor.com to run the build there in addition to Circle.
